### ISSUE TITLE
Error 403 when creating a customer

### ISSUE THREAD

**Issue by grebo-guru** [IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp#1]
Appears to do nothing when creating a customer. A trace shows that an IdsException is being thrown which gives Error 403 Forbidden. "Ids service endpoint was not found".

My workaround is to edit `Services.cs` method `QBOApiCall` and insert a line
before apiCallFunction() to set the BaseUrl.

```
ServiceContext context = new ServiceContext(token.RealmId, IntuitServicesType.QBO, reqValidator,configurationProvider);
context.IppConfiguration.BaseUrl.Qbo = "https://sandbox-quickbooks.api.intuit.com/";
apiCallFunction(context);
```
A better fix would be for Quickbooks dev to to update `ServiceContext` to read an entry from `appsettings.json`

**Comment by rkasaraneni20** [comment]
Can you please take the latest and try once. I updated the code now.
