### ISSUE TITLE
Sample does not appear to work

### ISSUE THREAD

**Issue by cbehrends** [IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp#4]
I added all of the credentials that it asked for.  It does authenticate and get a token, but then it fails with  "Forbidden" when any action is performed.

**Comment by nimisha84** [comment]
Enable fiddler logs or SDK logs and see what exact req is getting fired and what is the exact error message. You might be using the wrong base url for your calls- check whether the base url is for prod or sandbox based on your config

**Comment by nimisha84** [comment]
Check enabling logs docs here- https://github.com/intuit/QuickBooks-V3-DotNET-SDK

**Comment by cbehrends** [comment]
Here is what I get:

[14:17:28 VRB] Logging all headers in the request:
[14:17:28 VRB] Content-Type-application/xml
[14:17:28 VRB] Content-Type-application/xml
[14:17:28 VRB] Request Payload:<?xml version="1.0"?>
<Customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schema.intuit.com/finance/v3">
  <GivenName>Testing Company0.58199008860718</GivenName>
  <FamilyName>Testing Company0.54307366048129</FamilyName>
  <DisplayName>Testing Company0.45363199080044</DisplayName>
</Customer>
[14:17:28 VRB] Request Payload:<?xml version="1.0"?>
<Customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schema.intuit.com/finance/v3">
  <GivenName>Testing Company0.58199008860718</GivenName>
  <FamilyName>Testing Company0.54307366048129</FamilyName>
  <DisplayName>Testing Company0.45363199080044</DisplayName>
</Customer>
[14:17:30 VRB]  Response Intuit_Tid header: 1-5e67e7c8-717d0b5caf553bca40d89454, Response Payload: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2020-03-10T12:17:28.847-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="SERVICE">
        <Error code="3100">
            <Message>message=AuthorizationFailed; errorCode=003100; statusCode=403</Message>
        </Error>
    </Fault>
</IntuitResponse>

[14:17:30 VRB]  Response Intuit_Tid header: 1-5e67e7c8-717d0b5caf553bca40d89454, Response Payload: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2020-03-10T12:17:28.847-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="SERVICE">
        <Error code="3100">
            <Message>message=AuthorizationFailed; errorCode=003100; statusCode=403</Message>
        </Error>
    </Fault>
</IntuitResponse>

[14:17:30 VRB] Intuit.Ipp.Exception.IdsException: Forbidden ---> Intuit.Ipp.Exception.EndpointNotFoundException: Ids service endpoint was not found.

**Comment by nimisha84** [comment]
Ok, I see you are making a call to -request='quickbooks.api.intuit.com/v3/company/4620816365036670920/customer', method='POST', authType='oauth2'. Is this a sandbox company or a Prod? How did you authorize this company? If this a Prod company, can you invite me as and admin? Additionally, can you send me the complete fiddler logs for your calls starting from Authorization? Just follow the steps which the SDK ->Readme has for fiddler

**Comment by cbehrends** [comment]
I'm using this example to authorize.  

This is a test company, using the configs you provide other than my ClientID and Secret .

Am I just missing a config setting?

**Comment by nimisha84** [comment]
ok, then for a sandbox company you need to change the base url to sandbox.quickbooks.api.intuit.com.
It can be set on the ServiceContext object on the code or using config
https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net/configuration#base-url

**Comment by cbehrends** [comment]
That is what it's set to I think...

"BaseUrl": {
      "Qbo": "https://sandbox-quickbooks.api.intuit.com", //not supported- added for backward compatibility
      "Ips": "", //not supported-added for backward compatibility
      "OAuthAccessTokenUrl": "", //not supported-added for backward compatibility
      "UserNameAuthentication": ""
    },

**Comment by cbehrends** [comment]
Again, this is from the config in THIS REPOSITORY.

**Comment by nimisha84** [comment]
Add this line in your code-
ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.BaseUrl.Qbo = "https://sandbox-quickbooks.api.intuit.com/";

**Comment by cbehrends** [comment]
Hardcoding that in does appear to work.

How do I set this in the appsettings.json? Do I need to provide my own config var?

Once I get this all working I'll submit a pull request so that the sample works properly.

**Comment by nimisha84** [comment]
ok, the above setting in the config is obsolete and using your own config var would be recommended in it's place. Please submit your pull. Happy to get your feedback

**Comment by rbiq** [comment]
I was having the same exact issue. Your configuration provider doesn't use the BaseUrl
