### ISSUE TITLE
Is this fully workable project or in development status?

### ISSUE THREAD

**Issue by AhsanShuvo** [IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp#7]
I cloned this project and tried to run the project but it looks like callback does not work properly.

**Comment by rkasaraneni20** [comment]
Did you update the callback URL in portal... and may i know what is the error you are getting

**Comment by AhsanShuvo** [comment]
Yes.  It actually doesn't redirect to callback URL. After showing loading icon a long time, it shows `Site can not be reached`.
I updated my callback URL for both sites `http://localhost:44371/connect/index`

**Comment by rkasaraneni20** [comment]
@AhsanShuvo Can you see the authorization window when you click on `Connect to QuickBooks` button?
