### ISSUE TITLE
Issues with QBO page methods

### ISSUE THREAD

**Issue by edeliverysolutions** [IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp#8]
Hoping this helps someone who ran into these same issues as I was unable to find any help googling for several days.

This sample app did not work all the way for me.  The Connect method worked find but the QBO methods never worked (Create Customer / Create Invoice).

1.)
Initially I realized I had to manually enter the RealmId, AccessToken and RefreshToken into the SQLite database as it was not getting populated during the Connect method.  I think this may be as expected though?

2.)
Then when clicking the Create Customer button on the QBO.cshtml page, I encountered a null reference error at this line in the related method in the Services file -
 if (token.AccessToken != null && token.RealmId != null).   

This seemed to be caused by this preceding line not returning anything into the token due to the  _auth2Keys.RealmId value being null-
 var token = await _tokens.Token.FirstOrDefaultAsync(t => t.RealmId == _auth2Keys.RealmId);

To fix this I added a new line for RealmId to appSettings.json in the OAuth2Keys section and populated it with the QB company realmid value needed

3.) 
Next I received a special character in my access token error.  I had to add extra debugging to even see this error.  Upon more googling, it looks like the value coming from the database needed to be url encoded before being sent to QBO.

So these 2 lines i modifed in the Services QBOApiCall method to add the encoding and then everything finally worked all the way through--

(add using System.Web; at top of Services)
token.AccessToken = HttpUtility.UrlEncode(token.AccessToken);
token.RealmId = HttpUtility.UrlEncode(token.RealmId);

It would be great if these could be incorporated in the download so others don't have to go through this :)  It was a great learning experience though and thank you for getting us a .net core sample app for oauth2 and qbo, it is much appreciated.

**Comment by rkasaraneni20** [comment]
Thanks for the feedback @edeliverysolutions. You are correct on the 3rd point for some developers, will make a fix on that and for the first and second points that is expected to be updated by the developer as the realm Id differs for each developers. So we suggest the developers to go and update those values in the appSettings.json page.
